export type ResourceKind = 'crud' | 'list' | 'action' | 'summary';

export interface ResourceRouteDefinition {
  method: 'get' | 'post' | 'put' | 'patch' | 'delete';
  path: string;
  kind: ResourceKind;
  summary: string;
}

export const resourceRouteDefinitions: ResourceRouteDefinition[] = [
  { method: 'get', path: '/dashboard/summary', kind: 'summary', summary: 'dashboard summary' },
  { method: 'get', path: '/dashboard/agenda', kind: 'summary', summary: 'dashboard agenda' },
  { method: 'get', path: '/dashboard/health-snapshot', kind: 'summary', summary: 'dashboard health snapshot' },
  { method: 'get', path: '/dashboard/finance-snapshot', kind: 'summary', summary: 'dashboard finance snapshot' },
  { method: 'get', path: '/dashboard/life-snapshot', kind: 'summary', summary: 'dashboard life snapshot' },
  { method: 'get', path: '/dashboard/investment-snapshot', kind: 'summary', summary: 'dashboard investment snapshot' },
  { method: 'get', path: '/dashboard/notification-snapshot', kind: 'summary', summary: 'dashboard notification snapshot' },

  { method: 'get', path: '/notifications/channels', kind: 'crud', summary: 'list notification channels' },
  { method: 'post', path: '/notifications/channels', kind: 'crud', summary: 'create notification channel' },
  { method: 'patch', path: '/notifications/channels/:id', kind: 'crud', summary: 'update notification channel' },
  { method: 'get', path: '/notifications/scenes', kind: 'crud', summary: 'list notification scenes' },
  { method: 'patch', path: '/notifications/scenes/:id', kind: 'crud', summary: 'update notification scene' },
  { method: 'get', path: '/notifications/templates', kind: 'crud', summary: 'list notification templates' },
  { method: 'patch', path: '/notifications/templates/:id', kind: 'crud', summary: 'update notification template' },
  { method: 'get', path: '/notifications/logs', kind: 'list', summary: 'list notification logs' },
  { method: 'post', path: '/notifications/actions/test-channel', kind: 'action', summary: 'test notification channel' },
  { method: 'post', path: '/notifications/actions/send-scene', kind: 'action', summary: 'send notification scene' },

  { method: 'get', path: '/health/step/records', kind: 'crud', summary: 'list step records' },
  { method: 'post', path: '/health/step/records', kind: 'crud', summary: 'create step record' },
  { method: 'patch', path: '/health/step/records/:id', kind: 'crud', summary: 'update step record' },
  { method: 'delete', path: '/health/step/records/:id', kind: 'crud', summary: 'delete step record' },
  { method: 'get', path: '/health/step/summary', kind: 'summary', summary: 'step summary' },
  { method: 'get', path: '/health/step/trend', kind: 'summary', summary: 'step trend' },
  { method: 'get', path: '/health/step/month-compare', kind: 'summary', summary: 'step month compare' },

  { method: 'get', path: '/health/fitness/diet-records', kind: 'crud', summary: 'list diet records' },
  { method: 'post', path: '/health/fitness/diet-records', kind: 'crud', summary: 'create diet record' },
  { method: 'patch', path: '/health/fitness/diet-records/:id', kind: 'crud', summary: 'update diet record' },
  { method: 'delete', path: '/health/fitness/diet-records/:id', kind: 'crud', summary: 'delete diet record' },
  { method: 'get', path: '/health/fitness/exercise-records', kind: 'crud', summary: 'list exercise records' },
  { method: 'post', path: '/health/fitness/exercise-records', kind: 'crud', summary: 'create exercise record' },
  { method: 'patch', path: '/health/fitness/exercise-records/:id', kind: 'crud', summary: 'update exercise record' },
  { method: 'delete', path: '/health/fitness/exercise-records/:id', kind: 'crud', summary: 'delete exercise record' },
  { method: 'get', path: '/health/fitness/shopping-records', kind: 'crud', summary: 'list fitness shopping records' },
  { method: 'post', path: '/health/fitness/shopping-records', kind: 'crud', summary: 'create fitness shopping record' },
  { method: 'patch', path: '/health/fitness/shopping-records/:id', kind: 'crud', summary: 'update fitness shopping record' },
  { method: 'delete', path: '/health/fitness/shopping-records/:id', kind: 'crud', summary: 'delete fitness shopping record' },
  { method: 'get', path: '/health/fitness/weight-records', kind: 'crud', summary: 'list weight records' },
  { method: 'post', path: '/health/fitness/weight-records', kind: 'crud', summary: 'create weight record' },
  { method: 'patch', path: '/health/fitness/weight-records/:id', kind: 'crud', summary: 'update weight record' },
  { method: 'delete', path: '/health/fitness/weight-records/:id', kind: 'crud', summary: 'delete weight record' },
  { method: 'get', path: '/health/fitness/summary', kind: 'summary', summary: 'fitness summary' },
  { method: 'get', path: '/health/fitness/insights', kind: 'summary', summary: 'fitness insights' },

  { method: 'get', path: '/health/checkup/records', kind: 'crud', summary: 'list checkup records' },
  { method: 'post', path: '/health/checkup/records', kind: 'crud', summary: 'create checkup record' },
  { method: 'patch', path: '/health/checkup/records/:id', kind: 'crud', summary: 'update checkup record' },
  { method: 'delete', path: '/health/checkup/records/:id', kind: 'crud', summary: 'delete checkup record' },
  { method: 'get', path: '/health/checkup/templates', kind: 'crud', summary: 'list checkup templates' },
  { method: 'post', path: '/health/checkup/templates', kind: 'crud', summary: 'create checkup template' },
  { method: 'patch', path: '/health/checkup/templates/:id', kind: 'crud', summary: 'update checkup template' },
  { method: 'delete', path: '/health/checkup/templates/:id', kind: 'crud', summary: 'delete checkup template' },
  { method: 'post', path: '/health/checkup/actions/batch-create', kind: 'action', summary: 'batch create checkup records' },
  { method: 'get', path: '/health/checkup/overview', kind: 'summary', summary: 'checkup overview' },
  { method: 'get', path: '/health/checkup/trend', kind: 'summary', summary: 'checkup trend' },
  { method: 'get', path: '/health/checkup/insights', kind: 'summary', summary: 'checkup insights' },
  { method: 'post', path: '/health/checkup/actions/trigger-reminders', kind: 'action', summary: 'trigger checkup reminders' },

  { method: 'get', path: '/health/medication/records', kind: 'crud', summary: 'list medication records' },
  { method: 'post', path: '/health/medication/records', kind: 'crud', summary: 'create medication record' },
  { method: 'patch', path: '/health/medication/records/:id', kind: 'crud', summary: 'update medication record' },
  { method: 'delete', path: '/health/medication/records/:id', kind: 'crud', summary: 'delete medication record' },
  { method: 'get', path: '/health/medication/purchases', kind: 'crud', summary: 'list medication purchases' },
  { method: 'post', path: '/health/medication/purchases', kind: 'crud', summary: 'create medication purchase' },
  { method: 'patch', path: '/health/medication/purchases/:id', kind: 'crud', summary: 'update medication purchase' },
  { method: 'delete', path: '/health/medication/purchases/:id', kind: 'crud', summary: 'delete medication purchase' },
  { method: 'get', path: '/health/medication/summaries', kind: 'crud', summary: 'list medication summaries' },
  { method: 'post', path: '/health/medication/summaries', kind: 'crud', summary: 'create medication summary' },
  { method: 'patch', path: '/health/medication/summaries/:id', kind: 'crud', summary: 'update medication summary' },
  { method: 'delete', path: '/health/medication/summaries/:id', kind: 'crud', summary: 'delete medication summary' },
  { method: 'get', path: '/health/medication/overview', kind: 'summary', summary: 'medication overview' },
  { method: 'get', path: '/health/medication/analysis', kind: 'summary', summary: 'medication analysis' },
  { method: 'get', path: '/health/medication/stock', kind: 'summary', summary: 'medication stock summary' },
  { method: 'post', path: '/health/medication/actions/trigger-dose-reminder', kind: 'action', summary: 'trigger dose reminder' },
  { method: 'post', path: '/health/medication/actions/trigger-stock-reminder', kind: 'action', summary: 'trigger stock reminder' },

  { method: 'get', path: '/finance/shopping/records', kind: 'crud', summary: 'list shopping records' },
  { method: 'post', path: '/finance/shopping/records', kind: 'crud', summary: 'create shopping record' },
  { method: 'patch', path: '/finance/shopping/records/:id', kind: 'crud', summary: 'update shopping record' },
  { method: 'delete', path: '/finance/shopping/records/:id', kind: 'crud', summary: 'delete shopping record' },
  { method: 'get', path: '/finance/shopping/ledgers', kind: 'crud', summary: 'list shopping ledgers' },
  { method: 'post', path: '/finance/shopping/ledgers', kind: 'crud', summary: 'create shopping ledger' },
  { method: 'patch', path: '/finance/shopping/ledgers/:id', kind: 'crud', summary: 'update shopping ledger' },
  { method: 'delete', path: '/finance/shopping/ledgers/:id', kind: 'crud', summary: 'delete shopping ledger' },
  { method: 'get', path: '/finance/shopping/platforms', kind: 'crud', summary: 'list shopping platforms' },
  { method: 'post', path: '/finance/shopping/platforms', kind: 'crud', summary: 'create shopping platform' },
  { method: 'patch', path: '/finance/shopping/platforms/:id', kind: 'crud', summary: 'update shopping platform' },
  { method: 'delete', path: '/finance/shopping/platforms/:id', kind: 'crud', summary: 'delete shopping platform' },
  { method: 'get', path: '/finance/shopping/overview', kind: 'summary', summary: 'shopping overview' },
  { method: 'get', path: '/finance/shopping/monthly-trend', kind: 'summary', summary: 'shopping monthly trend' },
  { method: 'get', path: '/finance/shopping/platform-breakdown', kind: 'summary', summary: 'shopping platform breakdown' },
  { method: 'get', path: '/finance/shopping/ledger-summary', kind: 'summary', summary: 'shopping ledger summary' },
  { method: 'post', path: '/finance/shopping/actions/import', kind: 'action', summary: 'import shopping workbook' },

  { method: 'get', path: '/finance/travel/books', kind: 'crud', summary: 'list travel books' },
  { method: 'post', path: '/finance/travel/books', kind: 'crud', summary: 'create travel book' },
  { method: 'patch', path: '/finance/travel/books/:id', kind: 'crud', summary: 'update travel book' },
  { method: 'delete', path: '/finance/travel/books/:id', kind: 'crud', summary: 'delete travel book' },
  { method: 'get', path: '/finance/travel/records', kind: 'crud', summary: 'list travel records' },
  { method: 'post', path: '/finance/travel/records', kind: 'crud', summary: 'create travel record' },
  { method: 'patch', path: '/finance/travel/records/:id', kind: 'crud', summary: 'update travel record' },
  { method: 'delete', path: '/finance/travel/records/:id', kind: 'crud', summary: 'delete travel record' },
  { method: 'get', path: '/finance/travel/pay-channels', kind: 'crud', summary: 'list travel pay channels' },
  { method: 'post', path: '/finance/travel/pay-channels', kind: 'crud', summary: 'create travel pay channel' },
  { method: 'patch', path: '/finance/travel/pay-channels/:id', kind: 'crud', summary: 'update travel pay channel' },
  { method: 'delete', path: '/finance/travel/pay-channels/:id', kind: 'crud', summary: 'delete travel pay channel' },
  { method: 'get', path: '/finance/travel/summary', kind: 'summary', summary: 'travel summary' },
  { method: 'get', path: '/finance/travel/daily-trend', kind: 'summary', summary: 'travel daily trend' },
  { method: 'get', path: '/finance/travel/category-breakdown', kind: 'summary', summary: 'travel category breakdown' },
  { method: 'get', path: '/finance/travel/pay-channel-breakdown', kind: 'summary', summary: 'travel pay channel breakdown' },
  { method: 'get', path: '/finance/travel/leaderboard', kind: 'summary', summary: 'travel leaderboard' },
  { method: 'get', path: '/finance/travel/report', kind: 'summary', summary: 'travel report data' },
  { method: 'post', path: '/finance/travel/actions/import', kind: 'action', summary: 'import travel workbook' },
  { method: 'post', path: '/finance/travel/actions/export-report', kind: 'action', summary: 'export travel report' },

  { method: 'get', path: '/finance/loan/platforms', kind: 'crud', summary: 'list loan platforms' },
  { method: 'post', path: '/finance/loan/platforms', kind: 'crud', summary: 'create loan platform' },
  { method: 'patch', path: '/finance/loan/platforms/:id', kind: 'crud', summary: 'update loan platform' },
  { method: 'delete', path: '/finance/loan/platforms/:id', kind: 'crud', summary: 'delete loan platform' },
  { method: 'get', path: '/finance/loan/bills', kind: 'crud', summary: 'list loan bills' },
  { method: 'post', path: '/finance/loan/bills', kind: 'crud', summary: 'create loan bill' },
  { method: 'patch', path: '/finance/loan/bills/:id', kind: 'crud', summary: 'update loan bill' },
  { method: 'delete', path: '/finance/loan/bills/:id', kind: 'crud', summary: 'delete loan bill' },
  { method: 'get', path: '/finance/loan/repayments', kind: 'crud', summary: 'list loan repayments' },
  { method: 'post', path: '/finance/loan/repayments', kind: 'crud', summary: 'create loan repayment' },
  { method: 'patch', path: '/finance/loan/repayments/:id', kind: 'crud', summary: 'update loan repayment' },
  { method: 'delete', path: '/finance/loan/repayments/:id', kind: 'crud', summary: 'delete loan repayment' },
  { method: 'get', path: '/finance/loan/overview', kind: 'summary', summary: 'loan overview' },
  { method: 'get', path: '/finance/loan/monthly-stats', kind: 'summary', summary: 'loan monthly stats' },
  { method: 'get', path: '/finance/loan/repayment-trend', kind: 'summary', summary: 'loan repayment trend' },
  { method: 'get', path: '/finance/loan/platform-breakdown', kind: 'summary', summary: 'loan platform breakdown' },
  { method: 'get', path: '/finance/loan/settings', kind: 'crud', summary: 'get loan settings' },
  { method: 'patch', path: '/finance/loan/settings', kind: 'crud', summary: 'update loan settings' },
  { method: 'post', path: '/finance/loan/actions/mark-bill-paid', kind: 'action', summary: 'mark loan bill paid' },
  { method: 'post', path: '/finance/loan/actions/trigger-reminders', kind: 'action', summary: 'trigger loan reminders' },

  { method: 'get', path: '/finance/subscription/records', kind: 'crud', summary: 'list subscription records' },
  { method: 'post', path: '/finance/subscription/records', kind: 'crud', summary: 'create subscription record' },
  { method: 'patch', path: '/finance/subscription/records/:id', kind: 'crud', summary: 'update subscription record' },
  { method: 'delete', path: '/finance/subscription/records/:id', kind: 'crud', summary: 'delete subscription record' },
  { method: 'get', path: '/finance/subscription/categories', kind: 'crud', summary: 'list subscription categories' },
  { method: 'post', path: '/finance/subscription/categories', kind: 'crud', summary: 'create subscription category' },
  { method: 'patch', path: '/finance/subscription/categories/:id', kind: 'crud', summary: 'update subscription category' },
  { method: 'delete', path: '/finance/subscription/categories/:id', kind: 'crud', summary: 'delete subscription category' },
  { method: 'get', path: '/finance/subscription/overview', kind: 'summary', summary: 'subscription overview' },
  { method: 'get', path: '/finance/subscription/category-breakdown', kind: 'summary', summary: 'subscription category breakdown' },
  { method: 'get', path: '/finance/subscription/expiry-timeline', kind: 'summary', summary: 'subscription expiry timeline' },
  { method: 'get', path: '/finance/subscription/settings', kind: 'crud', summary: 'get subscription settings' },
  { method: 'patch', path: '/finance/subscription/settings', kind: 'crud', summary: 'update subscription settings' },
  { method: 'get', path: '/finance/subscription/reminders', kind: 'summary', summary: 'subscription reminders' },
  { method: 'post', path: '/finance/subscription/actions/trigger-reminders', kind: 'action', summary: 'trigger subscription reminders' },

  { method: 'get', path: '/finance/rent/records', kind: 'crud', summary: 'list rent records' },
  { method: 'post', path: '/finance/rent/records', kind: 'crud', summary: 'create rent record' },
  { method: 'patch', path: '/finance/rent/records/:id', kind: 'crud', summary: 'update rent record' },
  { method: 'delete', path: '/finance/rent/records/:id', kind: 'crud', summary: 'delete rent record' },
  { method: 'get', path: '/finance/rent/channels', kind: 'crud', summary: 'list rent channels' },
  { method: 'post', path: '/finance/rent/channels', kind: 'crud', summary: 'create rent channel' },
  { method: 'patch', path: '/finance/rent/channels/:id', kind: 'crud', summary: 'update rent channel' },
  { method: 'delete', path: '/finance/rent/channels/:id', kind: 'crud', summary: 'delete rent channel' },
  { method: 'get', path: '/finance/rent/overview', kind: 'summary', summary: 'rent overview' },
  { method: 'get', path: '/finance/rent/cost-breakdown', kind: 'summary', summary: 'rent cost breakdown' },
  { method: 'get', path: '/finance/rent/channel-breakdown', kind: 'summary', summary: 'rent channel breakdown' },
  { method: 'get', path: '/finance/rent/settings', kind: 'crud', summary: 'get rent settings' },
  { method: 'patch', path: '/finance/rent/settings', kind: 'crud', summary: 'update rent settings' },

  { method: 'get', path: '/life/todo/tasks', kind: 'crud', summary: 'list todo tasks' },
  { method: 'post', path: '/life/todo/tasks', kind: 'crud', summary: 'create todo task' },
  { method: 'patch', path: '/life/todo/tasks/:id', kind: 'crud', summary: 'update todo task' },
  { method: 'delete', path: '/life/todo/tasks/:id', kind: 'crud', summary: 'delete todo task' },
  { method: 'get', path: '/life/todo/overview', kind: 'summary', summary: 'todo overview' },
  { method: 'get', path: '/life/todo/settings', kind: 'crud', summary: 'get todo settings' },
  { method: 'patch', path: '/life/todo/settings', kind: 'crud', summary: 'update todo settings' },
  { method: 'post', path: '/life/todo/actions/batch-complete', kind: 'action', summary: 'batch complete todo tasks' },
  { method: 'post', path: '/life/todo/actions/batch-trash', kind: 'action', summary: 'batch trash todo tasks' },
  { method: 'post', path: '/life/todo/actions/restore', kind: 'action', summary: 'restore todo task' },
  { method: 'post', path: '/life/todo/actions/trigger-reminder', kind: 'action', summary: 'trigger todo reminder' },
  { method: 'get', path: '/life/todo/logs', kind: 'summary', summary: 'todo logs' },

  { method: 'get', path: '/life/card/cards', kind: 'crud', summary: 'list card records' },
  { method: 'post', path: '/life/card/cards', kind: 'crud', summary: 'create card record' },
  { method: 'patch', path: '/life/card/cards/:id', kind: 'crud', summary: 'update card record' },
  { method: 'delete', path: '/life/card/cards/:id', kind: 'crud', summary: 'delete card record' },
  { method: 'get', path: '/life/card/bills', kind: 'crud', summary: 'list card bills' },
  { method: 'post', path: '/life/card/bills', kind: 'crud', summary: 'create card bill' },
  { method: 'patch', path: '/life/card/bills/:id', kind: 'crud', summary: 'update card bill' },
  { method: 'delete', path: '/life/card/bills/:id', kind: 'crud', summary: 'delete card bill' },
  { method: 'get', path: '/life/card/recharges', kind: 'crud', summary: 'list card recharges' },
  { method: 'post', path: '/life/card/recharges', kind: 'crud', summary: 'create card recharge' },
  { method: 'delete', path: '/life/card/recharges/:id', kind: 'crud', summary: 'delete card recharge' },
  { method: 'get', path: '/life/card/carriers', kind: 'crud', summary: 'list card carriers' },
  { method: 'post', path: '/life/card/carriers', kind: 'crud', summary: 'create card carrier' },
  { method: 'patch', path: '/life/card/carriers/:id', kind: 'crud', summary: 'update card carrier' },
  { method: 'delete', path: '/life/card/carriers/:id', kind: 'crud', summary: 'delete card carrier' },
  { method: 'get', path: '/life/card/overview', kind: 'summary', summary: 'card overview' },
  { method: 'get', path: '/life/card/monthly-trend', kind: 'summary', summary: 'card monthly trend' },
  { method: 'get', path: '/life/card/carrier-breakdown', kind: 'summary', summary: 'card carrier breakdown' },
  { method: 'get', path: '/life/card/ranking', kind: 'summary', summary: 'card ranking' },
  { method: 'get', path: '/life/card/settings', kind: 'crud', summary: 'get card settings' },
  { method: 'patch', path: '/life/card/settings', kind: 'crud', summary: 'update card settings' },
  { method: 'post', path: '/life/card/actions/recharge', kind: 'action', summary: 'recharge card' },
  { method: 'post', path: '/life/card/actions/import-bills', kind: 'action', summary: 'import card bills' },
  { method: 'post', path: '/life/card/actions/trigger-reminders', kind: 'action', summary: 'trigger card reminders' },

  { method: 'get', path: '/life/storage/items', kind: 'crud', summary: 'list storage items' },
  { method: 'post', path: '/life/storage/items', kind: 'crud', summary: 'create storage item' },
  { method: 'patch', path: '/life/storage/items/:id', kind: 'crud', summary: 'update storage item' },
  { method: 'delete', path: '/life/storage/items/:id', kind: 'crud', summary: 'delete storage item' },
  { method: 'get', path: '/life/storage/overview', kind: 'summary', summary: 'storage overview' },
  { method: 'get', path: '/life/storage/purchase-trend', kind: 'summary', summary: 'storage purchase trend' },
  { method: 'get', path: '/life/storage/cost-ranking', kind: 'summary', summary: 'storage cost ranking' },
  { method: 'get', path: '/life/storage/settings', kind: 'crud', summary: 'get storage settings' },
  { method: 'patch', path: '/life/storage/settings', kind: 'crud', summary: 'update storage settings' },
  { method: 'post', path: '/life/storage/actions/archive', kind: 'action', summary: 'archive storage item' },
  { method: 'post', path: '/life/storage/actions/restore', kind: 'action', summary: 'restore storage item' },

  { method: 'get', path: '/investment/forex/trades', kind: 'crud', summary: 'list forex trades' },
  { method: 'post', path: '/investment/forex/trades', kind: 'crud', summary: 'create forex trade' },
  { method: 'patch', path: '/investment/forex/trades/:id', kind: 'crud', summary: 'update forex trade' },
  { method: 'delete', path: '/investment/forex/trades/:id', kind: 'crud', summary: 'delete forex trade' },
  { method: 'get', path: '/investment/forex/capital-flows', kind: 'crud', summary: 'list forex capital flows' },
  { method: 'post', path: '/investment/forex/capital-flows', kind: 'crud', summary: 'create forex capital flow' },
  { method: 'patch', path: '/investment/forex/capital-flows/:id', kind: 'crud', summary: 'update forex capital flow' },
  { method: 'delete', path: '/investment/forex/capital-flows/:id', kind: 'crud', summary: 'delete forex capital flow' },
  { method: 'get', path: '/investment/forex/dashboard-summary', kind: 'summary', summary: 'forex dashboard summary' },
  { method: 'get', path: '/investment/forex/daily-pnl-trend', kind: 'summary', summary: 'forex daily pnl trend' },
  { method: 'get', path: '/investment/forex/instrument-summary', kind: 'summary', summary: 'forex instrument summary' },
  { method: 'get', path: '/investment/forex/insights', kind: 'summary', summary: 'forex insights' },
  { method: 'post', path: '/investment/forex/calculator', kind: 'action', summary: 'forex calculator' },
  { method: 'post', path: '/investment/forex/actions/import', kind: 'action', summary: 'import forex workbook' },
  { method: 'get', path: '/investment/forex/actions/download-template', kind: 'action', summary: 'download forex template' },
];
